#![allow(dead_code, clippy::all, unused)]
use crate::finding::{Diagnostic, Severity};
use serde_json::Value;
const MAX_BODY: usize = 1 << 20;
const MAX_SUM: usize = 4096;
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Advisory {
    pub id: String,
    pub summary: String,
    pub severity: Severity,
}
#[rustfmt::skip] pub fn check_size(b:&[u8])->Result<(),Diagnostic>{if b.len()>MAX_BODY{Err(Diagnostic{code:"advisory-invalid",path:String::new(),rule:String::new(),message:"response too large".into()})}else{Ok(())}}
#[rustfmt::skip] pub fn is_valid_id(id:&str)->bool{if id.is_empty()||id.len()>128||id.contains('/')||id.contains('\\')||id.contains('\0'){return false;}let l=id.to_ascii_lowercase();if l.contains("..")||l.contains("<script")||l=="nan"{return false;}let mut c=id.chars();match c.next(){Some(x) if x.is_ascii_uppercase()=>{},_=>return false,}for ch in c{if !matches!(ch,'A'..='Z'|'0'..='9'|':'|'.'|'_'|'-'){return false;}}true}
#[rustfmt::skip] pub fn sanitize_summary(s:&str)->String{let mut t:String=s.chars().filter(|c|!c.is_control()||*c=='\n'||*c=='\t').collect();if t.len()>MAX_SUM{t.truncate(t.floor_char_boundary(MAX_SUM));}t}
#[rustfmt::skip] pub fn severity_for(cvss:Option<f64>)->Severity{match cvss{Some(v) if v>=9.0=>Severity::Critical,Some(v) if v>=7.0=>Severity::High,Some(v) if v>=4.0=>Severity::Medium,Some(v) if v>0.0=>Severity::Low,_=>Severity::High}}
#[rustfmt::skip] fn max_cvss(v:&Value)->Option<f64>{let arr=v.get("severity")?.as_array()?;let mut max:Option<f64>=None;for e in arr{let s=e.get("score")?.as_str()?;let f:f64=s.parse().ok()?;max=Some(max.map_or(f,|m|m.max(f)));}max}
#[rustfmt::skip] pub fn is_withdrawn(v:&Value)->bool{v.get("withdrawn").is_some_and(|x|!x.is_null())}
#[rustfmt::skip] pub fn validate_advisory(v:&Value)->Result<Option<Advisory>,Diagnostic>{let f=|m:&str|Diagnostic{code:"advisory-invalid",path:String::new(),rule:String::new(),message:m.into()};if is_withdrawn(v){return Ok(None);}let id=v.get("id").and_then(|x|x.as_str()).ok_or_else(||f("advisory-invalid"))?;if !is_valid_id(id){return Err(f("advisory-invalid"));}let raw=v.get("summary").and_then(|x|x.as_str()).unwrap_or("");let summary=sanitize_summary(raw);let sev=severity_for(max_cvss(v));Ok(Some(Advisory{id:id.into(),summary,severity:sev}))}
#[cfg(test)]
#[rustfmt::skip] mod tests{use super::*;fn no_leak(d:&Diagnostic,raw:&str){assert!(!d.message.contains(raw)&&!d.message.contains("<script")&&!d.message.contains(".."))}#[test]fn all(){assert!(check_size(&vec![b'a';MAX_BODY+1]).is_err());assert!(check_size(&vec![b'a';MAX_BODY]).is_ok());for bad in ["","lowercase","GHSA/abc","GHSA\\abc",&"A".repeat(129),"../etc/passwd","<script>alert(1)</script>","nan","GHSA-abc/../x"]{assert!(!is_valid_id(bad),"{bad}");}assert!(is_valid_id("GHSA-1234-5678-9012"));assert!(is_valid_id("CVE-2023-1234"));assert!(is_valid_id("PYSEC-2023-1"));let v=validate_advisory(&serde_json::json!({"id":"GHSA-1234","summary":"<script>x</script>"}));assert!(v.is_ok()&&v.unwrap().is_some());let bad2=serde_json::json!({"id":"<script>","summary":"x"});let e=validate_advisory(&bad2).unwrap_err();no_leak(&e,"<script>");let e2=validate_advisory(&serde_json::json!({"id":"../etc/passwd"}));assert!(e2.is_err());no_leak(&e2.unwrap_err(),"../");let nan=validate_advisory(&serde_json::json!({"id":"nan"}));assert!(nan.is_err());let withdrawn=validate_advisory(&serde_json::json!({"id":"GHSA-123","withdrawn":"2023-01-01T00:00:00Z"}));assert!(withdrawn.unwrap().is_none());let wnull=validate_advisory(&serde_json::json!({"id":"GHSA-123","withdrawn":null}));assert!(wnull.unwrap().is_some());for(cvss,exp) in [(Some(9.8),Severity::Critical),(Some(7.5),Severity::High),(Some(5.0),Severity::Medium),(Some(2.1),Severity::Low),(None,Severity::High)]{assert_eq!(severity_for(cvss),exp);}let vuln=serde_json::json!({"id":"GHSA-1","severity":[{"type":"CVSS_V3","score":"9.8"}]});assert_eq!(max_cvss(&vuln),Some(9.8));let adv=validate_advisory(&vuln).unwrap().unwrap();assert_eq!(adv.severity,Severity::Critical);let adv2=validate_advisory(&serde_json::json!({"id":"GHSA-2","severity":[{"type":"CVSS_V3","score":"2.1"}]})).unwrap().unwrap();assert_eq!(adv2.severity,Severity::Low);let miss=validate_advisory(&serde_json::json!({"id":"GHSA-3"})).unwrap().unwrap();assert_eq!(miss.severity,Severity::High);let big="a".repeat(5000);let adv3=validate_advisory(&serde_json::json!({"id":"GHSA-4","summary":big})).unwrap().unwrap();assert!(adv3.summary.len()<=4096);let ml="🦀".repeat(2000);let adv4=validate_advisory(&serde_json::json!({"id":"GHSA-5","summary":ml})).unwrap().unwrap();assert!(adv4.summary.len()<=4096&&adv4.summary.len()%"🦀".len()==0);}}
